#image: python:3.6-alpine

image: node
# node has git
# python:3.6-alpine has sphinx

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- build
- test
- deploy
- docs

build:
  stage: build
  script:
  - ./gradlew clean build -x test
  only:
  - /release/.*$/

unit tests:
  stage: test
  script:
  - ./gradlew test
  only:
  - /release/.*$/


publish_snapshot:
  stage: deploy
  script:
  - ./gradlew clean release -x test

  environment:
    name: publish_snapshot
  when: manual
  only:
  - /release/.*$/

publish_release:
  stage: deploy
  script:
  - ./gradlew clean release -x test

  environment:
    name: publish_release
  when: manual
  only:
  - /release/.*$/
  - master

generate_docs:
  stage: docs
  environment:
    name: generate_docs
#  when: manual
  only:
  - feature/auto-docs
  - master
  before_script:
  - mkdir -p ~/.ssh
  - mkdir -p ~/web3j-docs
  - chmod -R 700 ~/.ssh
  - chmod -R 700 ~/web3j-docs
  - git clone https://github.com/web3j/web3j.git ~/web3j-docs
  - cd ~/web3j-docs
  - git checkout gh-pages

  script:
  - apt-get update
  - apt-get install -y -qq python3-sphinx
  - apt-get install -y -qq python3-sphinx_rtd_theme
#  - apt-get install -y -qq npm curl
#  - pip install sphinx
#  - pip install sphinx_rtd_theme
  - cd /builds/web3j/web3j/docs
  - make clean html
#  - cp -Rf build/html/* ~/web3j-docs
#  - echo "Done"


